INSERT INTO TAG (NAME, EXPLANATION) VALUES('자바','자바의 설명');
INSERT INTO TAG (NAME, EXPLANATION) VALUES('자바스크립트','자바스크립트의 설명');
INSERT INTO TAG (NAME, EXPLANATION) VALUES('파이썬','파이썬의 설명');
INSERT INTO TAG (NAME, EXPLANATION) VALUES('제이슨','제이슨의 설명');
INSERT INTO TAG (NAME, EXPLANATION) VALUES('테스트','테스트의 설명');
INSERT INTO USERS (USER_ID, COUNTRY, EMAIL, INTRODUCTION, LINK, NICKNAME, PASSWORD, REPUTATION, TITLE) VALUES (1,'한국','aaa@gmail.com','ㅎㅇ','aaa@github.com','닉네임','비밀번호',100,'타이틀');

